CREATE TABLE ALIMENTOS (
  id BIGINT AUTO_INCREMENT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  descricao VARCHAR(255),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
CREATE TABLE REFEICAO (
  id BIGINT AUTO_INCREMENT NOT NULL,
  data date NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE REFEICAO_TEM_ALIMENTOS (
  refeicao_id bigint(20) NOT NULL,
  alimento_id bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE REFEICAO_TEM_ALIMENTOS
  ADD KEY FK_REFEICAO_TEM_ALIMENTO_ID (refeicao_id),
  ADD KEY FK_ALIMENTO_TEM_REFEICAO_ID (alimento_id);
  
ALTER TABLE REFEICAO_TEM_ALIMENTOS
  ADD CONSTRAINT FK_REFEICAO_TEM_ALIMENTO_ID FOREIGN KEY (refeicao_id) REFERENCES refeicao (id),
  ADD CONSTRAINT FK_ALIMENTO_TEM_REFEICAO_ID FOREIGN KEY (alimento_id) REFERENCES alimentos (id);
 
COMMIT;
 
INSERT INTO ALIMENTOS VALUES (1, 'Arroz', 'Cereal');
INSERT INTO ALIMENTOS VALUES (2, 'Feijão', 'Cereal');
INSERT INTO ALIMENTOS VALUES (3, 'Carne', 'Proteína Animal');
INSERT INTO ALIMENTOS VALUES (4, 'Salada', 'Vegetais');

COMMIT;


