CREATE TABLE CURSO (
  id BIGINT AUTO_INCREMENT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TURMA (
  id BIGINT AUTO_INCREMENT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;

INSERT INTO CURSO VALUES (1, 'Integrado em Informática');
INSERT INTO CURSO VALUES (2, 'Integrado em Guia de Turismo');
INSERT INTO CURSO VALUES (3, 'Subsequente em Agropecuária');
INSERT INTO CURSO VALUES (4, 'Subsequente em Alimentos');
INSERT INTO CURSO VALUES (5, 'Subsequente em Agrimensura');
INSERT INTO CURSO VALUES (6, 'Superior em Agroecologia');
INSERT INTO CURSO VALUES (7, 'Superior em Gestão em Turismo');
INSERT INTO CURSO VALUES (8, 'Superior em Engenharia de Alimentos');
INSERT INTO CURSO VALUES (9, 'EAD em Vendas');

INSERT INTO TURMA VALUES (1, 'I Semestre');
INSERT INTO TURMA VALUES (2, 'II Semestre');
INSERT INTO TURMA VALUES (3, 'III Semestre');
INSERT INTO TURMA VALUES (4, 'VI Semestre');
INSERT INTO TURMA VALUES (5, 'V Semestre');
INSERT INTO TURMA VALUES (6, 'VI Semestre');
INSERT INTO TURMA VALUES (7, 'VII Semestre');
INSERT INTO TURMA VALUES (8, 'VIII Semestre');
INSERT INTO TURMA VALUES (9, 'IX Semestre');
INSERT INTO TURMA VALUES (10, 'X Semestre');
INSERT INTO TURMA VALUES (11, '1 Ano');
INSERT INTO TURMA VALUES (12, '2 Ano');
INSERT INTO TURMA VALUES (13, '3 Ano');

COMMIT;